name: Stock Analysis Bot

on:
  schedule:
    - cron: '0 9 * * 1-5'  # 每周一到五16:00(UTC+8)运行
  workflow_dispatch:  # 允许手动触发

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install fonts-wqy-zenhei  # 解决中文显示问题

    - name: Run analysis
      env:
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        TZ: ${{ secrets.TZ }}
      run: |
        mkdir -p results  # 确保结果目录存在
        python 2.py --mode strict
